### ISSUE TITLE
:meta private: tag does not work

### ISSUE THREAD

**Issue by LeptoFlare** [ammaraskar/sphinx-action#22] opened 2021-02-18 02:19 UTC
Some of my docstrings include the `:meta private:` attribute.

When I build the html files from source, the proper methods are hidden.

However, when using the action, the attribute is not used and even shows up in the documentation:
![image](https://user-images.githubusercontent.com/47790183/108295488-c70bb180-7165-11eb-9422-e4a3543e8c16.png)

**Comment by ammaraskar** [comment] 2021-04-27 14:39
Hey Lepto, it looks like `:meta private:` was introduced in Sphinx 3.0+ which is why this doesn't work right now. I'm looking into allowing users to customize their sphinx version in https://github.com/ammaraskar/sphinx-action/issues/25, so I'm gonna close this as a duplicate of that.

**Closed by ammaraskar** 2021-04-27 14:39 UTC
